jobs:
    - deployment: Run_E2E_Tests
      pool:
        vmImage: ubuntu-20.04
      container: mcr.microsoft.com/playwright:v1.27.1-focal
      environment: testing
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: Bash@3
              displayName: 'install dependencies'
              inputs:
                targetType: 'inline'
                failOnStderr: false
                script: |
                  npm ci
                  exit 0
            - task: Bash@3
              displayName: 'Run Playwright tests'
              inputs:
                targetType: 'inline'
                failOnStderr: false
                script: |
                  npx playwright test
            - task: PublishTestResults@2
              displayName: 'Publish test results'
              inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: 'e2e-junit-results.xml'
                searchFolder: 'playwright-report'
                mergeTestResults: true
                failTaskOnFailedTests: true
                testRunTitle: 'End-To-End Tests'