# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- poc/second-time

pool:
  vmImage: ubuntu-latest

parameters:
- name: test
  displayName: 'test'
  type: object
  default:
    first: value
    other: otherValue
    another: anotherValue

container: mcr.microsoft.com/playwright:v1.27.0-focal

steps:
  - checkout: self
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'npm run e2e'
      failOnStderr: true

